CREATE TABLE investments (
    id SERIAL PRIMARY KEY,
    vc_id INTEGER NOT NULL REFERENCES vc(id) ON DELETE CASCADE,
    company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    funding_year INTEGER,
    round_type VARCHAR(256),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (vc_id, company_id)
);
