CREATE TABLE vc (
    id SERIAL PRIMARY KEY,
    name VARCHAR(128),
    domain VARCHAR(255) NOT NULL UNIQUE,
    portfolio_page_endpoint VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
